config/routes.rb
Rails.application.routes.draw do
  # 認証ルート
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  scope :receiving_orders do
    # 受注一覧
    get '/', to: 'receiving_orders/index#index', as: :receiving_orders

    # 新規受注作成画面
    get '/:item_id/create', to: 'receiving_orders/create/index#index', as: :receiving_orders_create

    # 新規受注作成
    post '/:item_id/create/submit', to: 'receiving_orders/create/index#submit', as: :receiving_orders_create_submit

    # 受注編集
    get '/:receiving_order_id/edit', to: 'receiving_orders/edit/index#index', as: :receiving_orders_edit

    # 受注更新
    patch '/:receiving_order_id/edit/submit', to: 'receiving_orders/edit/index#submit', as: :receiving_orders_edit_submit

    # 受注検索
    get '/search', to: 'receiving_orders/index#search', as: :receiving_orders_search
  end

  scope :items do
    # 在庫一覧
    get '/', to: 'items/index#index', as: :items

    # 在庫検索
    get '/search', to: 'items/index#search', as: :items_search

    # 在庫編集
    get '/:item_id/edit', to: 'items/edit/index#index', as: :items_edit

    # 在庫更新
    patch '/:item_id/edit/submit', to: 'items/edit/index#submit', as: :items_edit_submit
  end

  scope :orders do
    # 発注一覧
    get '/', to: 'orders/index#index', as: :orders

    # 新規発注作成画面
    get '/:item_id/create', to: 'orders/create/index#index', as: :orders_create

    # 新規発注作成
    post '/:item_id/create/submit', to: 'orders/create/index#submit', as: :orders_create_submit

    # 発注キャンセル
    post '/:order_id/create/cancel', to: 'orders/create/index#cancel', as: :orders_create_cancel

    # 発注検索
    get '/search', to: 'orders/index#search', as: :orders_search
  end
end

app/models/receiving_order.rb
class ReceivingOrder < ApplicationRecord
  # relation
  belongs_to :item
  belongs_to :client
  belongs_to :worker

  # validation
  with_options presence: true do
    validates :slip_no, numericality: { only_integer: true }
    validates :order_date
    validates :quantity, numericality: { only_integer: true }
    validates :status
  end

  validates :notes, length: { maximum: 100 }

  # enum
  enum status: { '発行済み': 1, '受注(在庫無)': 2, '発注済み': 3 }

  # ransackable attributes
  def self.ransackable_attributes(auth_object = nil)
    ["slip_no", "order_date", "quantity", "notes"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["client", "item"]
  end
end

app/controllers/receiving_orders/create/index_controller.rb
class ReceivingOrders::Create::IndexController < ApplicationController
  before_action :authenticate_user!
  before_action :find_item
  before_action :create_obj

  require 'date'

  def index
    render 'receiving_orders/create/index'
  end

  def submit
    @new_order = @item.receiving_orders.build

    # 一意の伝票番号生成
    max_value = ReceivingOrder.maximum('slip_no')

    if max_value.nil?
      slip_no = 1
    else
      slip_no = max_value + 1
    end

    @new_order.slip_no = slip_no
    @new_order.order_date = DateTime.now
    @new_order.notes = receiving_order_params[:notes]
    @new_order.client_id = receiving_order_params[:client_id]
    @new_order.worker_id = receiving_order_params[:worker_id]

    # 数量が在庫数を上回っていたらステータスを「受注(在庫無)」に変更
    if receiving_order_params[:quantity].to_i > @item.stock
      @new_order.status = 2
    end

    @new_order.quantity = receiving_order_params[:quantity]

    if @new_order.valid?
      # 商品の在庫数から受注数を引く(在庫が足りている場合)
      if receiving_order_params[:quantity].to_i >= @item.stock
        @item.stock = @item.stock - receiving_order_params[:quantity].to_i
      end

      @item.save
      @new_order.save
      redirect_to receiving_orders_path, notice: '「' + @item.name + '」の受注が完了しました'
    else
        render 'receiving_orders/create/index', status: :unprocessable_entity
    end
  end


  # private method
  private

  def find_item
    @item = Item.find(params[:item_id])
  end

  def create_obj
    @order = ReceivingOrder.new
  end

  def receiving_order_params
    params.require(:receiving_order).permit(:quantity, :notes, :client_id, :worker_id)
  end
end

app/controllers/receiving_orders/edit/index_controller.rb
class ReceivingOrders::Edit::IndexController < ApplicationController
  before_action :authenticate_user!
  before_action :find_order

  def index
    render 'receiving_orders/edit/index'
  end

  def submit
    if @order.update(order_params)
      redirect_to receiving_orders_path, notice: "「伝票番号:#{@order.slip_no}」の情報を更新しました"
    else
      render 'receiving_orders/edit/index', status: :unprocessable_entity
    end
  end


  # private
  private
  def find_order
    @order = ReceivingOrder.find(params[:receiving_order_id])
  end

  def order_params
    params.require(:receiving_order).permit(:notes, :worker_id)
  end
end

app/controllers/receiving_orders/index_controller.rb
class ReceivingOrders::IndexController < ApplicationController
  before_action :authenticate_user!
  before_action :set_q

  def index
    @results = ReceivingOrder.all.page(params[:page])

    # 売り上げの合計を算出
    arr = []
    @results.each do |result|
      arr.push(result.quantity * result.item.price)
    end

    @total_sales = arr.sum

    render 'receiving_orders/index'
  end

  def search
    @results = @q.result(stock: 0).order(id: :desc).page(params[:page])

    # 売り上げの合計を算出
    arr = []
    @results.each do |result|
      arr.push(result.quantity * result.item.price)
    end

    @total_sales = arr.sum

    render 'receiving_orders/search'
  end


  # private
  private
  def set_q
    @q = ReceivingOrder.ransack(params[:q])
  end
end

app/helpers/receiving_orders/index_helper.rb
module ReceivingOrders::IndexHelper
  def show_total_order_amount(price, quantity)
    number_to_currency(price * quantity)
  end
end

app/views/receiving_orders/index.html.erb
<div class="wrap">
  <h2 class="basic-heading">受注一覧</h2>
  <div class="search-area">
    <h2 class="search-area__heading">検索条件</h2>
    <%= search_form_for @q, url: receiving_orders_search_path, class: 'search-form flex' do |search| %>
    <div class="search-form__item">
      <%= search.label :slip_no_eq, '伝票No', class: 'search-form__label' %>
      <%= search.text_field :slip_no_eq, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :order_date_gteq, '受注日', class: 'search-form__label' %>
      <%= search.date_field :order_date_gteq, class: 'search-form__date' %>
      <span>&#65374;</span>
      <%= search.date_field :order_date_lteq, class: 'search-form__date' %>
    </div>
    <div class="search-form__item">
      <%= search.label :client_name_cont, '受注先', class: 'search-form__label' %>
      <%= search.text_field :client_name_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :item_code_cont, '商品コード', class: 'search-form__label' %>
      <%= search.text_field :item_code_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :item_name_cont, '商品名', class: 'search-form__label' %>
      <%= search.text_field :item_name_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :quantity_eq, '容量', class: 'search-form__label' %>
      <%= search.text_field :quantity_eq, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :notes_cont, '備考', class: 'search-form__label' %>
      <%= search.text_field :notes_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <div class="search-form__submit-wrap">
      <%= search.submit '検索', class: 'search-form__submit' %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="receiving">
    <div class="receiving-head--upper flex">
      <%= link_to '新規作成', items_path, class: 'receiving__btn' %>
      <span class="receiving__number"><%= @results.size %>件</span>
    </div>
    <div class="receiving-head--lower flex">
      <%= paginate @results %>
      <p class="receiving__total">売上合計: <%= number_to_currency(@total_sales) %></p>
    </div>
    <% if @results.any? %>
    <div class="receiving__table-wrap">
      <table class="receiving__table">
        <tbody>
          <tr>
            <th></th>
            <th colspan="9">受注</th>
            <th>配達</th>
            <th colspan="2">注文</th>
            <th></th>
          </tr>
          <tr>
            <th>No.</th>
            <th>受注日</th>
            <th>受注先</th>
            <th>商品名</th>
            <th>数量</th>
            <th>単価</th>
            <th>合計</th>
            <th>備考</th>
            <th>売上日</th>
            <th>状態</th>
            <th>担当者</th>
            <th>日付</th>
            <th>注文先</th>
            <th></th>
          </tr>
          <% @results.each do |result| %>
          <tr class="<%= 'issued' if result.status == '発行済み' %>">
            <td><%= result.slip_no %></td>
            <td><%= result.order_date.strftime('%m/%d') %></td>
            <td><%= result.client.name %></td>
            <td><%= result.item.name %></td>
            <td><%= result.quantity %></td>
            <td><%= number_to_currency(result.item.price) %></td>
            <td><%= show_total_order_amount(result.item.price, result.quantity) %></td>
            <td><%= result.notes %></td>
            <td class="has-color"><%= result.order_date.strftime('%m/%d') %></td>
            <td class="has-color second <%= 'nis' if result.status == '受注(在庫無)' %>"><%= result.status %></td>
            <td><%= result.worker.name %></td>
            <td>test</td>
            <td>test</td>
            <td>
              <div class="flex">
                <%= link_to '編集', receiving_orders_edit_path(result), class: 'btn' %>
                <% if result.status == '受注(在庫無)' %>
                <%= link_to '発注', orders_create_path(result), class: 'btn' %>
                <% end %>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% else %>
    <p class="receiving__txt">受注データはありません</p>
    <% end %>
  </div>
</div>

app/views/receiving_orders/search.html.erb
<div class="wrap">
  <h2 class="basic-heading">受注一覧</h2>
  <div class="search-area">
    <h2 class="search-area__heading">検索条件</h2>
    <%= search_form_for @q, url: receiving_orders_search_path, class: 'search-form flex' do |search| %>
    <div class="search-form__item">
      <%= search.label :slip_no_eq, '伝票No', class: 'search-form__label' %>
      <%= search.text_field :slip_no_eq, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :order_date_gteq, '受注日', class: 'search-form__label' %>
      <%= search.date_field :order_date_gteq, class: 'search-form__date' %>
      <span>&#65374;</span>
      <%= search.date_field :order_date_lteq, class: 'search-form__date' %>
    </div>
    <div class="search-form__item">
      <%= search.label :client_name_cont, '受注先', class: 'search-form__label' %>
      <%= search.text_field :client_name_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :item_code_cont, '商品コード', class: 'search-form__label' %>
      <%= search.text_field :item_code_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :item_name_cont, '商品名', class: 'search-form__label' %>
      <%= search.text_field :item_name_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :quantity_eq, '商品名', class: 'search-form__label' %>
      <%= search.text_field :quantity_eq, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :notes_cont, '備考', class: 'search-form__label' %>
      <%= search.text_field :notes_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <div class="search-form__submit-wrap">
      <%= search.submit '検索', class: 'search-form__submit' %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="receiving">
    <div class="receiving-head--upper flex">
      <%= link_to '新規作成', items_path, class: 'receiving__btn' %>
      <span class="receiving__number"><%= @results.size %>件</span>
    </div>
    <div class="receiving-head--lower flex">
      <%= paginate @results %>
      <p class="receiving__total">売上合計: <%= number_to_currency(@total_sales) %></p>
    </div>
    <% if @results.any? %>
    <div class="receiving__table-wrap">
      <table class="receiving__table">
        <tbody>
          <tr>
            <th></th>
            <th colspan="9">受注</th>
            <th>配達</th>
            <th colspan="2">注文</th>
            <th></th>
          </tr>
          <tr>
            <th>No.</th>
            <th>受注日</th>
            <th>受注先</th>
            <th>商品名</th>
            <th>数量</th>
            <th>単価</th>
            <th>合計</th>
            <th>備考</th>
            <th>売上日</th>
            <th>状態</th>
            <th>担当者</th>
            <th>日付</th>
            <th>注文先</th>
            <th></th>
          </tr>
          <% @results.each do |result| %>
          <tr class="<%= 'issued' if result.status == '発行済み' %>">
            <td><%= result.slip_no %></td>
            <td><%= result.order_date.strftime('%m/%d') %></td>
            <td><%= result.client.name %></td>
            <td><%= result.item.name %></td>
            <td><%= result.quantity %></td>
            <td><%= number_to_currency(result.item.price) %></td>
            <td><%= show_total_order_amount(result.item.price, result.quantity) %></td>
            <td><%= result.notes %></td>
            <td class="has-color"><%= result.order_date.strftime('%m/%d') %></td>
            <td class="has-color second <%= 'nis' if result.status == '受注(在庫無)' %>"><%= result.status %></td>
            <td><%= result.worker.name %></td>
            <td>test</td>
            <td>test</td>
            <td>
              <div class="flex">
                <%= link_to '編集', receiving_orders_edit_path(result), class: 'btn' %>
                <% if result.status == '受注(在庫無)' %>
                <%= link_to '発注', orders_create_path(result), class: 'btn' %>
                <% end %>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% else %>
    <p class="receiving__txt">受注データはありません</p>
    <% end %>
  </div>
</div>