config/routes.rb
Rails.application.routes.draw do
  # 認証ルート
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  scope :receiving_orders do
    # 受注一覧
    get '/', to: 'receiving_orders/index#index', as: :receiving_orders

    # 新規受注作成画面
    get '/:item_id/create', to: 'receiving_orders/create/index#index', as: :receiving_orders_create

    # 新規受注作成
    post '/:item_id/create/submit', to: 'receiving_orders/create/index#submit', as: :receiving_orders_create_submit

    # 受注編集
    get '/:receiving_order_id/edit', to: 'receiving_orders/edit/index#index', as: :receiving_orders_edit

    # 受注更新
    patch '/:receiving_order_id/edit/submit', to: 'receiving_orders/edit/index#submit', as: :receiving_orders_edit_submit

    # 受注検索
    get '/search', to: 'receiving_orders/index#search', as: :receiving_orders_search
  end

  scope :items do
    # 在庫一覧
    get '/', to: 'items/index#index', as: :items

    # 在庫検索
    get '/search', to: 'items/index#search', as: :items_search

    # 在庫編集
    get '/:item_id/edit', to: 'items/edit/index#index', as: :items_edit

    # 在庫更新
    patch '/:item_id/edit/submit', to: 'items/edit/index#submit', as: :items_edit_submit
  end

  scope :orders do
    # 発注一覧
    get '/', to: 'orders/index#index', as: :orders

    # 新規発注作成画面
    get '/:item_id/create', to: 'orders/create/index#index', as: :orders_create

    # 新規発注作成
    post '/:item_id/create/submit', to: 'orders/create/index#submit', as: :orders_create_submit

    # 発注キャンセル
    post '/:order_id/create/cancel', to: 'orders/create/index#cancel', as: :orders_create_cancel

    # 発注検索
    get '/search', to: 'orders/index#search', as: :orders_search
  end
end

app/models/order.rb
class Order < ApplicationRecord
  # relation
  belongs_to :item
  belongs_to :supplier
  belongs_to :worker

  # validation
  with_options presence: true do
    validates :slip_no, numericality: { only_integer: true }
    validates :order_date
    validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
    validates :status
  end

  # enum
  enum status: { '発注済み': 1, 'キャンセル': 2 }

  # ransackable attributes
  def self.ransackable_attributes(auth_object = nil)
    ["order_date"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["supplier", "item"]
  end
end

app/controllers/orders/create/index_controller.rb
class Orders::Create::IndexController < ApplicationController
  before_action :authenticate_user!
  before_action :find_item, only: %i(index submit)
  before_action :create_obj, only: %i(index submit)

  require 'date'

  def index
    render 'orders/create/index'
  end

  def submit
    @new_order = @item.orders.build

    # 一意の伝票番号生成
    max_value = Order.maximum('slip_no')

    if max_value.nil?
      slip_no = 1
    else
      slip_no = max_value + 1
    end

    @new_order.slip_no = slip_no
    @new_order.order_date = DateTime.now
    @new_order.supplier_id = order_params[:supplier_id]
    @new_order.worker_id = order_params[:worker_id]

    # # 数量が在庫数を上回っていたらステータスを「受注(在庫無)」に変更
    # if receiving_order_params[:quantity].to_i > @item.stock
    #   @new_order.status = 2
    # end

    @new_order.quantity = order_params[:quantity]

    if @new_order.valid?
      # 商品の在庫数を変更
        @item.stock = order_params[:quantity].to_i

      @item.save
      @new_order.save
      redirect_to orders_path, notice: '「' + @item.name + '」の発注が完了しました'
    else
        render 'orders/create/index', status: :unprocessable_entity
    end
  end

  def cancel
    order = Order.find(params[:order_id])
    item = Item.find(params[:item_id])

    # 該当する発注ステータスをキャンセルに変更
    order.status = 2
    order.save

    # キャンセルした発注量分だけ、該当する商品から差し引く
    item.stock = item.stock - order.quantity
    item.save

    redirect_to orders_path
  end


  # private method
  private

  def find_item
    @item = Item.find(params[:item_id])
  end

  def create_obj
    @order = Order.new
  end

  def order_params
    params.require(:order).permit(:quantity, :supplier_id, :worker_id)
  end
end

app/controllers/orders/index_controller.rb
class Orders::IndexController < ApplicationController
  before_action :authenticate_user!
  before_action :set_q

  def index
    @results = Order.all.page(params[:page])

    render 'orders/index'
  end

  def search
    @results = @q.result(stock: 0).order(id: :desc).page(params[:page])

    render 'orders/search'
  end


  # private
  private
  def set_q
    @q = Order.ransack(params[:q])
  end
end

app/views/orders/index.html.erb
<div class="wrap">
  <h2 class="basic-heading">発注一覧</h2>
  <div class="search-area">
    <h2 class="search-area__heading">検索条件</h2>
    <%= search_form_for @q, url: orders_search_path, class: 'search-form flex' do |search| %>
    <div class="search-form__item">
      <%= search.label :supplier_name_cont, '発注先', class: 'search-form__label' %>
      <%= search.text_field :supplier_name_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :item_name_cont, '商品', class: 'search-form__label' %>
      <%= search.text_field :item_name_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :order_date_gteq, '発注日', class: 'search-form__label' %>
      <%= search.date_field :order_date_gteq, class: 'search-form__date' %>
      <span>&#65374;</span>
      <%= search.date_field :order_date_lteq, class: 'search-form__date' %>
    </div>
    <div class="search-form__item">
      <div class="search-form__submit-wrap">
      <%= search.submit '検索', class: 'search-form__submit' %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="receiving">
    <div class="receiving-head--upper flex">
      <span class="receiving__number"><%= @results.size %>件</span>
    </div>
    <div class="receiving-head--lower flex">
      <%= paginate @results %>
    </div>
    <% if @results.any? %>
    <div class="order__table-wrap">
    <table class="order__table">
      <tbody>
        <tr>
        <th>No</th>
        <th>発注先</th>
        <th>商品</th>
        <th>数量</th>
        <th>発注日</th>
        <th>手配者</th>
        <th>状態</th>
        <th></th>
        </tr>
        <% @results.each do |result| %>
        <tr class="<%= 'cancel' if result.status == 'キャンセル' %>">
        <td><%= result.slip_no %></td>
        <td><%= result.supplier.name %></td>
        <td><%= result.item.name %></td>
        <td><%= result.quantity %></td>
        <td><%= result.order_date.strftime('%m/%d') %></td>
        <td><%= result.worker.name %></td>
        <td><%= result.status %></td>
        <td>
          <% if result.status != 'キャンセル' %>
          <%= form_with(url: orders_create_cancel_path(result), data: { confirm: '本当にこの発注をキャンセルしますか? この操作は元に戻せません。', disable_with: 'loading...' }, class: 'order-cancel-form') do |form| %>
            <%= form.submit 'キャンセル', class: 'order-cancel-form__btn' %>
            <%= hidden_field_tag :item_id, result.item.id %>
          <% end %>
          <% end %>
        </td>
        </tr>
        <% end %>
  </tbody>
</table>
    </div>
    <% else %>
    <p class="receiving__txt">発注データはありません</p>
    <% end %>
  </div>
</div>

app/views/orders/search.html.erb
<div class="wrap">
  <h2 class="basic-heading">発注一覧</h2>
  <div class="search-area">
    <h2 class="search-area__heading">検索条件</h2>
    <%= search_form_for @q, url: orders_search_path, class: 'search-form flex' do |search| %>
    <div class="search-form__item">
      <%= search.label :supplier_name_cont, '発注先', class: 'search-form__label' %>
      <%= search.text_field :supplier_name_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :item_name_cont, '商品', class: 'search-form__label' %>
      <%= search.text_field :item_name_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.label :order_date_gteq, '発注日', class: 'search-form__label' %>
      <%= search.date_field :order_date_gteq, class: 'search-form__date' %>
      <span>&#65374;</span>
      <%= search.date_field :order_date_lteq, class: 'search-form__date' %>
    </div>
    <div class="search-form__item">
      <div class="search-form__submit-wrap">
      <%= search.submit '検索', class: 'search-form__submit' %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="receiving">
    <div class="receiving-head--upper flex">
      <span class="receiving__number"><%= @results.size %>件</span>
    </div>
    <div class="receiving-head--lower flex">
      <%= paginate @results %>
    </div>
    <% if @results.any? %>
    <div class="order__table-wrap">
    <table class="order__table">
      <tbody>
        <tr>
        <th>No</th>
        <th>発注先</th>
        <th>商品</th>
        <th>数量</th>
        <th>発注日</th>
        <th>手配者</th>
        <th>状態</th>
        <th></th>
        </tr>
        <% @results.each do |result| %>
        <tr class="<%= 'cancel' if result.status == 'キャンセル' %>">
        <td><%= result.slip_no %></td>
        <td><%= result.supplier.name %></td>
        <td><%= result.item.name %></td>
        <td><%= result.quantity %></td>
        <td><%= result.order_date.strftime('%m/%d') %></td>
        <td><%= result.worker.name %></td>
        <td><%= result.status %></td>
        <td>
          <% if result.status != 'キャンセル' %>
          <%= form_with(url: orders_create_cancel_path(result), data: { confirm: '本当にこの発注をキャンセルしますか? この操作は元に戻せません。', disable_with: 'loading...' }, class: 'order-cancel-form') do |form| %>
            <%= form.submit 'キャンセル', class: 'order-cancel-form__btn' %>
            <%= hidden_field_tag :item_id, result.item.id %>
          <% end %>
          <% end %>
        </td>
        </tr>
        <% end %>
  </tbody>
</table>
    </div>
    <% else %>
    <p class="receiving__txt">発注データはありません</p>
    <% end %>
  </div>
</div>