config/routes.rb
Rails.application.routes.draw do
  # 認証ルート
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  scope :receiving_orders do
    # 受注一覧
    get '/', to: 'receiving_orders/index#index', as: :receiving_orders

    # 新規受注作成画面
    get '/:item_id/create', to: 'receiving_orders/create/index#index', as: :receiving_orders_create

    # 新規受注作成
    post '/:item_id/create/submit', to: 'receiving_orders/create/index#submit', as: :receiving_orders_create_submit

    # 受注編集
    get '/:receiving_order_id/edit', to: 'receiving_orders/edit/index#index', as: :receiving_orders_edit

    # 受注更新
    patch '/:receiving_order_id/edit/submit', to: 'receiving_orders/edit/index#submit', as: :receiving_orders_edit_submit

    # 受注検索
    get '/search', to: 'receiving_orders/index#search', as: :receiving_orders_search
  end

  scope :items do
    # 在庫一覧
    get '/', to: 'items/index#index', as: :items

    # 在庫検索
    get '/search', to: 'items/index#search', as: :items_search

    # 在庫編集
    get '/:item_id/edit', to: 'items/edit/index#index', as: :items_edit

    # 在庫更新
    patch '/:item_id/edit/submit', to: 'items/edit/index#submit', as: :items_edit_submit
  end

  scope :orders do
    # 発注一覧
    get '/', to: 'orders/index#index', as: :orders

    # 新規発注作成画面
    get '/:item_id/create', to: 'orders/create/index#index', as: :orders_create

    # 新規発注作成
    post '/:item_id/create/submit', to: 'orders/create/index#submit', as: :orders_create_submit

    # 発注キャンセル
    post '/:order_id/create/cancel', to: 'orders/create/index#cancel', as: :orders_create_cancel

    # 発注検索
    get '/search', to: 'orders/index#search', as: :orders_search
  end
end

app/models/item.rb
class Item < ApplicationRecord
  # relation
  has_many :receiving_orders, dependent: :destroy
  has_many :orders, dependent: :destroy

  # validations
  with_options presence: true do
    validates :name, length: { maximum: 30 }
    validates :price, numericality: { only_integer: true, in: 300..99999 }
  end

  # ransackable attributes
  def self.ransackable_attributes(auth_object = nil)
    ["code", "name", "stock"]
  end
end

app/controllers/items/edit/index_controller.rb
class Items::Edit::IndexController < ApplicationController
  before_action :authenticate_user!
  before_action :find_item

  def index
    render 'items/edit/index'
  end

  def submit
    if @item.update(item_params)
      redirect_to items_path, notice: '商品情報を更新しました'
    else
      render 'items/edit/index'
    end
  end


  # private
  private
  def find_item
    @item = Item.find(params[:item_id])
  end

  def item_params
    params.require(:item).permit(:name, :price, :stock)
  end
end

app/controllers/items/index_controller.rb
class Items::IndexController < ApplicationController
  before_action :authenticate_user!
  before_action :set_q

  def index
    @results = Item.order(id: :desc).page(params[:page])

    render 'items/index'
  end

  def search
    if params[:q][:stock] == 1
      @results = @q.result(stock: 0).order(id: :desc).page(params[:page])
    else
      @results = @q.result.order(id: :desc).page(params[:page])
    end

    render 'items/search'
  end


  # private
  private
  def set_q
    @q = Item.ransack(params[:q])
  end
end

app/helpers/items/index_helper.rb
module Items::IndexHelper
  def show_total_amount(price, stock)
    number_to_currency(price * stock)
  end
end

app/views/items/index.html.erb
<div class="wrap">
  <h2 class="basic-heading">在庫照会</h2>
  <div class="search-area">
    <h2 class="search-area__heading">検索条件</h2>
    <%= search_form_for @q, url: items_search_path, class: 'search-form flex' do |search| %>
    <div class="search-form__item">
      <%= search.label :name_cont, '商品名', class: 'search-form__label' %>
      <%= search.text_field :name_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.check_box :stock_lt, { class: 'search-form__check' }, checked_value = 1, nil %>
      <%= search.label :stock_lt, '在庫切れのみ表示', class: 'search-form__label' %>
    </div>
    <div class="search-form__item">
      <div class="search-form__submit-wrap">
      <%= search.submit '検索', class: 'search-form__submit' %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="item">
    <div class="item__head flex">
      <%= paginate @results %>
      <span class="item__number"><%= @results.total_count %>件</span>
    </div>
    <% if @results.any? %>
    <div class="item__table-wrap">
      <table class="item__table">
        <tbody>
          <tr>
            <th class="code">商品コード</th>
            <th class="name">商品名</th>
            <th class="stock">在庫</th>
            <th class="amount">在庫金額</th>
            <th class="empty"></th>
          </tr>
          <% @results.each do |result| %>
          <tr class="<%= 'out-of-stock' if result.stock <= 0 %>">
            <td><%= result.code %></td>
            <td><%= result.name %></td>
            <td><%= result.stock %></td>
            <td><%= show_total_amount(result.price, result.stock) %></td>
            <td>
              <div class="flex">
                <% unless result.stock == 0 %>
                <%= link_to '編集', items_edit_path(result), class: 'btn' %>
                <% end %>
                <%= link_to '受注', receiving_orders_create_path(result), class: 'btn' %>
                <%= link_to '発注', orders_create_path(result), class: 'btn' %>
              </div>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% else %>
    <p class="item__txt">在庫データはありません</p>
    <% end %>
  </div>
</div>

app/views/items/search.html.erb
<div class="wrap">
  <h2 class="basic-heading">在庫照会</h2>
  <div class="search-area">
    <h2 class="search-area__heading">検索条件</h2>
    <%= search_form_for @q, url: items_search_path, class: 'search-form flex' do |search| %>
    <div class="search-form__item">
      <%= search.label :name_cont, '商品名', class: 'search-form__label' %>
      <%= search.text_field :name_cont, class: 'search-form__input' %>
    </div>
    <div class="search-form__item">
      <%= search.check_box :stock_lt, { class: 'search-form__check' }, checked_value = 1, nil %>
      <%= search.label :stock_lt, '在庫切れのみ表示', class: 'search-form__label' %>
    </div>
    <div class="search-form__item">
      <div class="search-form__submit-wrap">
      <%= search.submit '検索', class: 'search-form__submit' %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="item">
    <div class="item__head flex">
      <%= paginate @results %>
      <span class="item__number"><%= @results.total_count %>件</span>
    </div>
    <% if @results.any? %>
    <table class="item__table">
      <tbody>
        <tr>
          <th>商品コード</th>
          <th>商品名</th>
          <th>在庫</th>
          <th>在庫金額</th>
          <th></th>
        </tr>
        <% @results.each do |result| %>
        <tr class="<%= 'out-of-stock' if result.stock <= 0 %>">
          <td><%= result.code %></td>
          <td><%= result.name %></td>
          <td><%= result.stock %></td>
          <td><%= show_total_amount(result.price, result.stock) %></td>
          <td>
          <div class="flex">
            <% unless result.stock == 0 %>
            <%= link_to '編集', items_edit_path(result), class: 'btn' %>
            <% end %>
            <%= link_to '受注', receiving_orders_create_path(result), class: 'btn' %>
            <%= link_to '発注', orders_create_path(result), class: 'btn' %>
          </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
    <p class="item__txt">在庫データはありません</p>
    <% end %>
  </div>
</div>